import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class TermsAndConditionPage extends StatelessWidget {
  const TermsAndConditionPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: HtmlWidget("""
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>&iexcl;Bienvenido a Expose!</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Estos t&eacute;rminos y condiciones describen las reglas y regulaciones para el uso del sitio web de Expose S.A.S, ubicado en www.expose.com.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Al acceder a este sitio web, asumimos que aceptas estos t&eacute;rminos y condiciones. No contin&uacute;es usando Expose si no est&aacute;s de acuerdo con todos los t&eacute;rminos y condiciones establecidos en esta p&aacute;gina.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Cookies:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>El sitio web utiliza cookies para ayudar a personalizar tu experiencia en l&iacute;nea. Al acceder a Expose, aceptaste utilizar las cookies necesarias.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Una cookie es un archivo de texto que un servidor de p&aacute;ginas web coloca en tu disco duro. Las cookies no se pueden utilizar para ejecutar programas o enviar virus a tu computadora. Las cookies se te asignan de forma exclusiva y solo un servidor web en el dominio que emiti&oacute; la cookie puede leerlas.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Podemos utilizar cookies para recopilar, almacenar y rastrear informaci&oacute;n con fines estad&iacute;sticos o de marketing para operar nuestro sitio web. Tienes la capacidad de aceptar o rechazar cookies opcionales. Hay algunas cookies obligatorias que son necesarias para el funcionamiento de nuestro sitio web. Estas cookies no requieren tu consentimiento ya que siempre funcionan. Ten en cuenta que al aceptar las cookies requeridas, tambi&eacute;n aceptas las cookies de terceros, que podr&iacute;an usarse a trav&eacute;s de servicios proporcionados por terceros si utilizas dichos servicios en nuestro sitio web, por ejemplo, una ventana de visualizaci&oacute;n de video proporcionada por terceros e integrada en nuestro sitio web.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Licencia:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>A menos que se indique lo contrario, Expose S.A.S y/o sus licenciantes poseen los derechos de propiedad intelectual de todo el material en Expose. Todos los derechos de propiedad intelectual son reservados. Puedes acceder desde Expose para tu uso personal sujeto a las restricciones establecidas en estos t&eacute;rminos y condiciones.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>No debes:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Copiar o volver a publicar material de Expose</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Vender, alquilar o sublicenciar material de Expose</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Reproducir, duplicar o copiar material de Expose</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Redistribuir contenido de Expose</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Este acuerdo comenzar&aacute; el fecha presente.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Partes de este sitio web ofrecen a los usuarios la oportunidad de publicar e intercambiar opiniones e informaci&oacute;n en determinadas &aacute;reas. Expose S.A.S no filtra, edita, publica ni revisa los comentarios antes de su presencia en el sitio web. Los comentarios no reflejan los puntos de vista ni las opiniones de Expose S.A.S, sus agentes y/o afiliados. Los comentarios reflejan los puntos de vista y opiniones de la persona que publica. En la medida en que lo permitan las leyes aplicables, Expose S.A.S no ser&aacute; responsable de los comentarios ni de ninguna responsabilidad, da&ntilde;os o gastos causados o sufridos como resultado de cualquier uso o publicaci&oacute;n o apariencia de comentarios en este sitio web.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Expose S.A.S se reserva el derecho de monitorear todos los comentarios y eliminar los que puedan considerarse inapropiados, ofensivos o que incumplan estos T&eacute;rminos y Condiciones.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Garantizas y declaras que:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Tienes derecho a publicar comentarios en nuestro sitio web y tienes todas las licencias y consentimientos necesarios para hacerlo;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Los comentarios no invaden ning&uacute;n derecho de propiedad intelectual, incluidos, entre otros, los derechos de autor, patentes o marcas comerciales de terceros;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Los comentarios no contienen ning&uacute;n material difamatorio, calumnioso, ofensivo, indecente o ilegal de otro modo, que sea una invasi&oacute;n de la privacidad.</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Los comentarios no se utilizar&aacute;n para solicitar o promover negocios o actividades comerciales personalizadas o presentes o actividades ilegales.</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Por la presente, otorgas a Expose S.A.S una licencia no exclusiva para usar, reproducir, editar y autorizar a otros a usar, reproducir y editar cualquiera de tus comentarios en todas y cada una de las formas, formatos, o medios.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Hiperv&iacute;nculos a nuestro contenido:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Las siguientes organizaciones pueden vincularse a nuestro sitio web sin aprobaci&oacute;n previa por escrito:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Agencias gubernamentales;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Motores de b&uacute;squeda;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Organizaciones de noticias;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Los distribuidores de directorios en l&iacute;nea pueden vincularse a nuestro sitio web de la misma manera que hacen hiperv&iacute;nculos a los sitios web de otras empresas que figuran en la lista; y</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Empresas acreditadas en todo el sistema, excepto que soliciten organizaciones sin fines de lucro, centros comerciales de caridad y grupos de recaudaci&oacute;n de fondos de caridad que no pueden hacer hiperv&iacute;nculos a nuestro sitio web.</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Estas organizaciones pueden enlazar a nuestra p&aacute;gina de inicio, a publicaciones o a otra informaci&oacute;n del sitio siempre que el enlace: (a) no sea enga&ntilde;oso de ninguna manera; (b) no implique falsamente patrocinio, respaldo o aprobaci&oacute;n de la parte vinculante y sus productos y/o servicios; y (c) encaja en el contexto del sitio de la parte vinculante.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Podemos considerar y aprobar otras solicitudes de enlaces de los siguientes tipos de organizaciones:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>fuentes de informaci&oacute;n de consumidores y/o empresas com&uacute;nmente conocidas;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>sitios de la comunidad .com;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>asociaciones u otros grupos que representan organizaciones ben&eacute;ficas;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>distribuidores de directorios en l&iacute;nea;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>portales de Internet;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>firmas de contabilidad, derecho y consultor&iacute;a; y</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>instituciones educativas y asociaciones comerciales.</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Aprobaremos las solicitudes de enlace de estas organizaciones si: (a) el enlace no nos har&iacute;a vernos desfavorablemente a nosotros mismos ni a nuestras empresas acreditadas; (b) la organizaci&oacute;n no tiene registros negativos con nosotros; (c) el beneficio para nosotros de la visibilidad del hiperv&iacute;nculo compensa la ausencia de Expose S.A.S; y (d) el enlace est&aacute; en el contexto de informaci&oacute;n general de recursos.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Estas organizaciones pueden enlazar a nuestra p&aacute;gina de inicio siempre que el enlace: (a) no sea enga&ntilde;oso de ninguna manera; (b) no implique falsamente patrocinio, respaldo o aprobaci&oacute;n de la parte vinculante y sus productos o servicios; y (c) encaja en el contexto del sitio de la parte vinculante.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Si eres una de las organizaciones enumeradas en el p&aacute;rrafo 2 y est&aacute;s interesada en vincularte a nuestro sitio web, debes informarnos enviando un correo electr&oacute;nico a Expose S.A.S. Incluye tu nombre, el nombre de tu organizaci&oacute;n, la informaci&oacute;n de contacto, as&iacute; como la URL de tu sitio, una lista de las URL desde las que tienes la intenci&oacute;n de vincular a nuestro sitio web y una lista de las URL de nuestro sitio a las que te gustar&iacute;a acceder. Espera 2-3 semanas para recibir una respuesta.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Las organizaciones aprobadas pueden hacer hiperv&iacute;nculos a nuestro sitio web de la siguiente manera:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Mediante el uso de nuestro nombre corporativo; o</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Mediante el uso del localizador uniforme de recursos al que se est&aacute; vinculando; o</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>Usar cualquier otra descripci&oacute;n de nuestro sitio web al que est&aacute; vinculado que tenga sentido dentro del contexto y formato del contenido en el sitio de la parte vinculante.</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>No se permitir&aacute; el uso del logotipo de Expose S.A.S u otro material gr&aacute;fico para vincular sin un acuerdo de licencia de marca comercial.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Responsabilidad del contenido:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>No seremos responsables de ning&uacute;n contenido que aparezca en tu sitio web. Aceptas protegernos y defendernos contra todas las reclamaciones que se presenten en tu sitio web. Ning&uacute;n enlace(s) debe aparecer en ning&uacute;n sitio web que pueda interpretarse como difamatorio, obsceno o criminal, o que infrinja, de otra manera viole o defienda la infracci&oacute;n u otra violaci&oacute;n de los derechos de terceros.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Reserva de derechos:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Nos reservamos el derecho de solicitar que elimines todos los enlaces o cualquier enlace en particular a nuestro sitio web. Apruebas eliminar de inmediato todos los enlaces a nuestro sitio web cuando se solicite. Tambi&eacute;n nos reservamos el derecho de modificar estos t&eacute;rminos y condiciones y su pol&iacute;tica de enlaces en cualquier momento. Al vincular continuamente a nuestro sitio web, aceptas estar vinculado y seguir estos t&eacute;rminos y condiciones de vinculaci&oacute;n.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Eliminaci&oacute;n de enlaces de nuestro sitio web:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Si encuentras alg&uacute;n enlace en nuestro sitio que sea ofensivo por cualquier motivo, puedes contactarnos e informarnos en cualquier momento. Consideraremos las solicitudes para eliminar enlaces, pero no estamos obligados a hacerlo ni a responder directamente.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>No nos aseguramos de que la informaci&oacute;n de este sitio web sea correcta. No garantizamos su integridad o precisi&oacute;n, ni prometemos asegurarnos de que el sitio web permanezca disponible o que el material en el sitio se mantenga actualizado.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Exenci&oacute;n de responsabilidad:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>En la medida m&aacute;xima permitida por la ley aplicable, excluimos todas las representaciones, garant&iacute;as y condiciones relacionadas con nuestro sitio web y el uso de este. Nada en este descargo de responsabilidad:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>limitar&aacute; o excluir&aacute; nuestra responsabilidad o la tuya por muerte o lesiones personales;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>limitar&aacute; o excluir&aacute; nuestra responsabilidad o la tuya por fraude o tergiversaci&oacute;n fraudulenta;</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>limitar&aacute; cualquiera de nuestras responsabilidades o las tuyas de cualquier manera que no est&eacute; permitida por la ley aplicable; o</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#474B4F;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;'>excluir&aacute; cualquiera de nuestras responsabilidades o las tuyas que no puedan estar excluidas seg&uacute;n la ley aplicable.</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Las limitaciones y prohibiciones de responsabilidad establecidas en esta secci&oacute;n y en otras partes de este descargo de responsabilidad: (a) est&aacute;n sujetas al p&aacute;rrafo anterior; y (b) regir&aacute; todas las responsabilidades que surjan en virtud de la exenci&oacute;n de responsabilidad, incluidas las responsabilidades que surjan en el contrato, en agravio y por incumplimiento de la obligaci&oacute;n legal.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:#474B4F;'>Siempre que el sitio web y la informaci&oacute;n y los servicios en el sitio se proporcionen de forma gratuita, no seremos responsables de ninguna p&eacute;rdida o da&ntilde;o de cualquier naturaleza.</span></p>
"""),
    );
  }
}
